using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// Lightsaber Script: Attached to the FlamingSword prefab. Controls movement and damage detection for the clone generated by the Weapon.
//
// Issue: Why can't I access the boxCollider component when inheriting from the Colliderable class??
// Solution: Here, use the logic from the Colliderable class as is.
public class FlamingSword : MonoBehaviour
{
    private Vector3 originalSize;       // Original size of the lightsaber
    private float nowTime;              // Timer
    public float lifeTime = 0.5f;       // Duration of the lightsaber

    public ContactFilter2D filter;
    private BoxCollider2D boxCollider;
    private Collider2D[] hits = new Collider2D[10];

    private void Start()
    {
        boxCollider = GetComponent<BoxCollider2D>();

        // The initial position of the lightsaber is in front of the Player
        Vector3 pos = GameManager.instance.player.transform.position;
        pos.y = GameManager.instance.player.transform.position.y - 0.02f;

        // Adjust direction
        originalSize = GetComponent<Transform>().localScale;
        if (GameManager.instance.player.transform.localScale.x > 0)
        {
            transform.localScale = originalSize;
            pos.x += 0.1f;
        }
        else if (GameManager.instance.player.transform.localScale.x < 0)
        {
            transform.localScale = new Vector3(originalSize.x * -1, originalSize.y, originalSize.y);
            pos.x -= 0.1f;
        }

        nowTime = Time.time;
        gameObject.transform.position = pos;
    }

    private void Update()
    {
        if (Time.time - nowTime > lifeTime)
            Destroy(gameObject);

        // Get a list of all colliders that overlap with this Collider
        boxCollider.OverlapCollider(filter, hits);
        for (int i = 0; i < hits.Length; i++)
        {
            if (hits[i] == null)
                continue;

            OnCollide(hits[i]);

            hits[i] = null;
        }

        // Move the lightsaber
        // It is recommended to increase the speed here; slow speed may cause multiple collisions with Enemy, resulting in multiple instances of damage
        transform.position += Vector3.right * Time.deltaTime * transform.localScale.x * 3f;
    }

    private void OnCollide(Collider2D coll)
    {
        if (coll.tag == "Fighter")
        {
            if (coll.name == "Player")
                return;

            Damag dmg = new Damag
            {
                // Damage and push distance for the enemy are twice the current weapon's values
                damageAmount = GameManager.instance.weapon.damagePoint[GameManager.instance.weapon.weaponLevel] * 2,
                origin = transform.position,
                pushForce = GameManager.instance.weapon.pushForce[GameManager.instance.weapon.weaponLevel] * 2
            };

            // Send a message to the collided object, calling its ReceiveDamage function (inside the Fighter class)
            coll.SendMessage("ReceiveDamage", dmg);
        }
    }
}
